# $HOME/.config/alacritty/alacritty.toml

# specification: https://alacritty.org/config-alacritty.html

# uses a theme from https://github.com/alacritty/alacritty-theme
import = [
    "~/.config/alacritty/themes/themes/afterglow.toml"
]

[window]
opacity = 1.0
padding.x = 10
padding.y = 10
decorations = "Full"
decorations_theme_variant = "Dark"
startup_mode = "Fullscreen"

[font]
normal.family = "JetBrainsMono Nerd Font"
bold.family = "JetBrainsMono Nerd Font"
italic.family = "JetBrainsMono Nerd Font"
bold_italic.family = "JetBrainsMono Nerd Font"
size = 12.0

[cursor]
style.shape = "Beam"

[mouse]
hide_when_typing = true
